Folder to be saved in: #provide the folder to be saved in
Session cookie: #provide the session cookie
Number of entries: #provide the number of entries - should be integer
User name: #provide the username